### ISSUE TITLE
Missing property fieldMappings in constructor SearchIndexer 

### ISSUE THREAD

**Issue by Arimov** [Azure-Samples/azure-search-dotnet-samples#66]
In the project `multiple-data-sources/v11` fields are mapped on line `145` 
https://github.com/Azure-Samples/azure-search-dotnet-samples/blob/1fb831067976a4f81d68746ceb4ec8cc5440da0d/multiple-data-sources/v11/src/Program.cs#L145

but variable `map` is not used, 
I think there should be some code like this  (line 155)
```C#
 SearchIndexer blobIndexer = new SearchIndexer(
	name: "hotel-rooms-blob-indexer",
	dataSourceName: blobDataSource.Name,
	targetIndexName: indexName)
{
	Parameters = parameters,
	FieldMappings = map,
	Schedule = new IndexingSchedule(TimeSpan.FromDays(1))
};
```

**Comment by JerryMWeeks** [comment]
This has had me confused too @Arimov - the line numbers have changed a little since but
I think the list<fieldMapping> variable named map is completely redundant (and unused), because precisely the same is redeclared at line 164 in the code:
` blobIndexer.FieldMappings.Add(new FieldMapping("Id") { TargetFieldName = "HotelId" });`

doing the same as the unused lines 154-150:
` List<FieldMapping> map = new List<FieldMapping> {
                new FieldMapping("Id")
                {
                    TargetFieldName =  "HotelId"
                }
            };`

**Comment by HeidiSteen** [comment]
This issue is fixed. Thanks for reporting the issue.
